/// Flutter icons Flutter1
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Flutter1
///      fonts:
///       - asset: fonts/Flutter1.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Flutter1 {
  Flutter1._();

  static const _kFontFam = 'Flutter1';
  static const _kFontPkg = null;

  static const IconData medical = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
