/// Flutter icons Flutter2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Flutter2
///      fonts:
///       - asset: fonts/Flutter2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Flutter2 {
  Flutter2._();

  static const _kFontFam = 'Flutter2';
  static const _kFontPkg = null;

  static const IconData bell = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
