/// Flutter icons Flutter
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Flutter
///      fonts:
///       - asset: fonts/Flutter.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Flutter {
  Flutter._();

  static const _kFontFam = 'Flutter1';
  static const _kFontPkg = null;

  static const IconData man = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
